name: "Replicate File"
description: "Copy a file from one repository to another (direct write to default branch)"
inputs:
  source_owner:
    description: "Source repository owner"
    required: true
  source_repo:
    description: "Source repository name"
    required: true
  source_path:
    description: "Path in source repository"
    required: true
  target_owner:
    description: "Target repository owner"
    required: true
  target_repo:
    description: "Target repository name"
    required: true
  overwrite:
    description: "Overwrite if the file already exists (true/false)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: "Replicate"
      uses: actions/github-script@v7
      env:
        SOURCE_OWNER: ${{ inputs.source_owner }}
        SOURCE_REPO: ${{ inputs.source_repo }}
        SOURCE_PATH: ${{ inputs.source_path }}
        TARGET_OWNER: ${{ inputs.target_owner }}
        TARGET_REPO: ${{ inputs.target_repo }}
        OVERWRITE: ${{ inputs.overwrite }}
      with:
        script: |
          const owner = process.env.SOURCE_OWNER;
          const repo = process.env.SOURCE_REPO;
          const path = process.env.SOURCE_PATH;
          const targetOwner = process.env.TARGET_OWNER;
          const targetRepo = process.env.TARGET_REPO;
          const overwrite = process.env.OVERWRITE === "true";

          // 1. Get source file
          const sourceRes = await github.rest.repos.getContent({
            owner,
            repo,
            path
          });
          
          if (sourceRes.data.type !== "file") {
            throw new Error("Source path is not a file");
          }
          
          const content = sourceRes.data.content;
          const fileSha = sourceRes.data.sha;

          // 2. Get target default branch
          const repoInfo = await github.rest.repos.get({
            owner: targetOwner,
            repo: targetRepo
          });
          const defaultBranch = repoInfo.data.default_branch;

          // 3. Check if file exists in target
          let existingSha = null;
          try {
            const existingRes = await github.rest.repos.getContent({
              owner: targetOwner,
              repo: targetRepo,
              path
            });
            existingSha = existingRes.data.sha;
          } catch (e) {
            if (e.status !== 404) throw e;
          }

          if (existingSha && !overwrite) {
            throw new Error("File already exists in target repository. Set overwrite=true to replace it.");
          }

          // 4. Create or update in target
          await github.rest.repos.createOrUpdateFileContents({
            owner: targetOwner,
            repo: targetRepo,
            path,
            message: `chore: replicate ${path} from ${owner}/${repo}`,
            content,
            branch: defaultBranch,
            ...(existingSha ? { sha: existingSha } : {})
          });
          
          core.info("Replication completed.");
