name: "Create Sprint"
description: "Create milestone and minimal sprint issues"

inputs:
  version:
    description: "Version (e.g. v1.4.0)"
    required: true
  description:
    description: "Short sprint description"
    required: false

runs:
  using: "composite"
  steps:
    - name: Create Milestone
      id: create_milestone
      uses: actions/github-script@v7
      with:
        script: |
          const milestone = await github.rest.issues.createMilestone({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ inputs.version }}",
            description: "${{ inputs.description || '' }}"
          });

          core.setOutput("milestone_number", milestone.data.number);

    - name: Create Sprint Issues
      uses: actions/github-script@v7
      with:
        script: |
          const milestoneNumber = "${{ steps.create_milestone.outputs.milestone_number }}";
          const version = "${{ inputs.version }}";

          const issues = [
            `Sprint ${version} 定義`,
            `Sprint ${version} 実作業`,
            `Sprint ${version} タグ作成`
          ];

          for (const title of issues) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              milestone: milestoneNumber
            });
          }
