name: "Create Sprint"
description: "Create milestone and minimal sprint issues"

inputs:
  version:
    description: "Version (e.g. v1.4.0)"
    required: true
  description:
    description: "Short sprint description"
    required: false

runs:
  using: "composite"
  steps:
    - name: Create Milestone and Issues
      uses: actions/github-script@v7
      with:
        script: |
          const version = "${{ inputs.version }}";
          const desc = "${{ inputs.description || '' }}";

          const milestone = await github.rest.issues.createMilestone({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: version,
            description: desc
          });

          const milestoneNumber = milestone.data.number;

          const templates = [
            {
              title: `Sprint ${version} 定義`,
              body: `# Sprint Definition\n\n- Version: ${version}\n- Goal:\n`
            },
            {
              title: `Sprint ${version} 実作業`,
              body: `# Sprint Work\n\n- [ ] Implementation complete\n- [ ] Merged into main\n`
            },
            {
              title: `Sprint ${version} タグ作成`,
              body: `# Tag Creation\n\n- [ ] Ready to tag\n- [ ] Tag pushed\n`
            }
          ];

          for (const issue of templates) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issue.title,
              body: issue.body,
              milestone: milestoneNumber
            });
          }
