name: "Initialize Request"
description: "Create a new branch, add .create-request marker, and open a Draft Pull Request"

inputs:
  title:
    description: "Request title"
    required: true
  intent:
    description: "Optional detailed description"
    required: false
  branch_name:
    description: "Optional branch name override (without prefix)"
    required: false

outputs:
  branch_name:
    description: "Created branch name"
    value: ${{ steps.initialize.outputs.branch_name }}
  pr_number:
    description: "Created Pull Request number"
    value: ${{ steps.initialize.outputs.pr_number }}
  pr_url:
    description: "Created Pull Request URL"
    value: ${{ steps.initialize.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: "Initialize"
      id: initialize
      uses: actions/github-script@v7
      env:
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_INTENT: ${{ inputs.intent }}
        INPUT_BRANCH_NAME: ${{ inputs.branch_name }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      with:
        script: |
          const owner = process.env.REPO_OWNER;
          const repo = process.env.REPO_NAME;
          const title = process.env.INPUT_TITLE;
          if (!title) throw new Error("title is required");
          const intent = process.env.INPUT_INTENT || "";
          const branchOverride = process.env.INPUT_BRANCH_NAME;

          const repoInfo = await github.rest.repos.get({ owner, repo });
          const defaultBranch = repoInfo.data.default_branch;

          const { data: refData } = await github.rest.git.getRef({
            owner,
            repo,
            ref: `heads/${defaultBranch}`
          });
          const baseSha = refData.object.sha;

          function slugify(str) {
            return str
              .toLowerCase()
              .replace(/[^a-z]0-9-]/g, "")
              .trim()
              .replace(/\s+/g, "-");
          }

          const slug = slugify(title);
          const finalBranch = branchOverride ? `request/${branchOverride}` : `request/${slug}`;

          await github.rest.git.createRef({
            owner,
            repo,
            ref: `refs/heads/${finalBranch}`,
            sha: baseSha
          });

          const markerContent = Buffer.from(finalBranch + "\n").toString("base64");

          await github.rest.repos.createOrUpdateFileContents({
            owner,
            repo,
            path: ".create-request",
            message: "chore: initialize request branch",
            content: markerContent,
            branch: finalBranch
          });

          const prResp = await github.rest.pulls.create({
            owner,
            repo,
            title,
            head: finalBranch,
            base: defaultBranch,
            body: intent,
            draft: true
          });

          core.setOutput("branch_name", finalBranch);
          core.setOutput("pr_number", prResp.data.number);
          core.setOutput("pr_url", prResp.data.html_url);
        