name: "Initialize Request"
description: "Step 1: Create Milestone, branch, and Request Issues (Start/Completion)"

inputs:
  title:
    description: "Natural language request title"
    required: true
  intent:
    description: "Optional detailed intent or background"
    required: false
  branch_name:
    description: "Optional branch name override (without prefix)"
    required: false

outputs:
  milestone_number:
    description: "Created Milestone number"
    value: ${{ steps.initialize.outputs.milestone_number }}

  branch_name:
    description: "Created branch name"
    value: ${{ steps.initialize.outputs.branch_name }}

runs:
  using: "composite"
  steps:
    - name: "Initialize Request"
      uses: actions/github-script@v7
      env:
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_INTENT: ${{ inputs.intent }}
        INPUT_BRANCH_NAME: ${{ inputs.branch_name }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      with:
        script: |
          const owner = process.env.REPO_OWNER;
          const repo = process.env.REPO_NAME;

          const title = process.env.INPUT_TITLE;
          if (!title) throw new Error("title input is required");

          const intent = process.env.INPUT_INTENT;
          const branchOverride = process.env.INPUT_BRANCH_NAME;

          const milestoneResp = await github.rest.issues.createMilestone({
            owner,
            repo,
            title,
            description: intent || ""
          });

          const milestoneNumber = milestoneResp.data.number;


          // 1. default branch 取得
          const repoInfo = await github.rest.repos.get({
            owner,
            repo
          });

          const defaultBranch = repoInfo.data.default_branch;

          // 2. default branch の SHA 取得
          const { data: refData } = await github.rest.git.getRef({
            owner,
            repo,
            ref: `heads/${defaultBranch}`
          });

          const baseSha = refData.object.sha;

          // 3. branch 名決定
          function slugify(str) {
            return str
              .toLowerCase()
              .replace(/[^a-z0-9\s-]/g, "")
              .trim()
              .replace(/\s+/g, "-");
          }

          const slug = slugify(title);

          const finalBranch = branchOverride
            ? `request/${branchOverride}`
            : `request/${slug}`;

          // 4. branch 作成
          await github.rest.git.createRef({
            owner,
            repo,
            ref: `refs/heads/${finalBranch}`,
            sha: baseSha
          });






          // テンプレート読み込みのためリポジトリからファイル取得
          async function fetchTemplate(path) {
            const resp = await github.rest.repos.getContent({
              owner,
              repo,
              path,
              ref: finalBranch
            });
            return Buffer.from(resp.data.content, "base64").toString("utf8");
          }

          function parseTemplate(raw) {
            const lines = raw.split("\n");
            const titleLine = lines.find(l => l.startsWith("TITLE:"));
            const titleSuffix = titleLine ? titleLine.replace("TITLE:", "").trim() : "";
            const body = lines.filter(l => !l.startsWith("TITLE:")).join("\n").trimStart();
            return { titleSuffix, body };
          }

          const startRaw = await fetchTemplate(".github/actions/create-request/templates/request-start.md");
          const completionRaw = await fetchTemplate(".github/actions/create-request/templates/request-completion.md");

          const start = parseTemplate(startRaw);
          const completion = parseTemplate(completionRaw);

          await github.rest.issues.create({
            owner,
            repo,
            title: `${start.titleSuffix}: ${title}`,
            body: start.body,
            milestone: milestoneNumber
          });

          await github.rest.issues.create({
            owner,
            repo,
            title: `${completion.titleSuffix}: ${title}`,
            body: completion.body,
            milestone: milestoneNumber
          });

          core.setOutput("milestone_number", milestoneNumber);
          core.setOutput("branch_name", finalBranch);
