name: "Initialize Request"
description: "Step 1: Create Milestone, branch, and Request Issues (Start/Completion)"

inputs:
  title:
    description: "Natural language request title"
    required: true
  intent:
    description: "Optional detailed intent or background"
    required: false
  branch_name:
    description: "Optional branch name override (without prefix)"
    required: false

outputs:
  milestone_number:
    description: "Created Milestone number"
  branch_name:
    description: "Created branch name"

runs:
  using: "composite"
  steps:
    - name: "Initialize Request"
      uses: actions/github-script@v7
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          const title = core.getInput("title", { required: true });
          const intent = core.getInput("intent");
          const branchOverride = core.getInput("branch_name");

          const milestoneResp = await github.rest.issues.createMilestone({
            owner,
            repo,
            title,
            description: intent || ""
          });

          const milestoneNumber = milestoneResp.data.number;

          const repoInfo = await github.rest.repos.get({
            owner,
            repo
          });

          const defaultBranch = repoInfo.data.default_branch;

          const refData = await github.rest.git.getRef({
            owner,
            repo,
            ref: `[heads/${defaultBranch}]
          });

          const baseSha = refData.data.object.sha;

          function slugify(str) {
            return str
              .toLowerCase()
              .replace(/[^a-z\-9\\s-]/g, "")
              .trim()
              .replace(/\s+/g, "-");
          }

          const slug = slugify(title);
          const finalBranch = branchOverride
            ? `request/${branchOverride}`
            : `request/${slug}`;

          await github.rest.git.createRef({});

          await github.rest.issues.create({});

          core.setOutput("milestone_number", milestoneNumber);
          core.setOutput("branch_name", finalBranch);
