name: "Initialize Request"
description: "Create a new branch with an empty commit and open a structured Draft Pull Request"

inputs:
  title:
    description: "Request title"
    required: true
  background:
    description: "Markdown-enabled background (use ### or smaller headings)"
    required: false
  approach:
    description: "Markdown-enabled approach (use ### or smaller headings)"
    required: false
  branch_name:
    description: "Optional branch name override (without prefix)"
    required: false

outputs:
  branch_name:
    description: "Created branch name"
    value: ${{ steps.initialize.outputs.branch_name }}
  pr_number:
    description: "Created Pull Request number"
    value: ${{ steps.initialize.outputs.pr_number }}
  pr_url:
    description: "Created Pull Request URL"
    value: ${{ steps.initialize.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: "Initialize"
      id: initialize
      uses: actions/github-script@v7
      env:
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_BACKGROUND: ${{ inputs.background }}
        INPUT_APPROACH: ${{ inputs.approach }}
        INPUT_BRANCH_NAME: ${{ inputs.branch_name }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      with:
        script: |
          const owner = process.env.REPO_OWNER;
          const repo = process.env.REPO_NAME;
          const title = process.env.INPUT_TITLE;
          if (!title) throw new Error("title is required");
          const background = process.env.INPUT_BACKGROUND || "";
          const approach = process.env.INPUT_APPROACH || "";
          const branchOverride = process.env.INPUT_BRANCH_NAME;
          const repoInfo = await github.rest.repos.get({ owner, repo });
          const defaultBranch = repoInfo.data.default_branch;
          const { data: refData } = await github.rest.git.getRef({ owner, repo, ref: `heads/${defaultBranch}` });
          const baseSha = refData.object.sha;
          const { data: baseCommit } = await github.rest.git.getCommit({ owner, repo, commit_sha: baseSha });
          const baseTreeSha = baseCommit.tree.sha;
          const slug = title.toLowerCase().replace(/[^a-z0-9-]/g, "").trim().replace(/\s+/g, "-");
          const finalBranch = branchOverride ? `request/${branchOverride}` : `request/${slug}`;
          await github.rest.git.createRef({ owner, repo, ref: `refs/heads/${finalBranch}`, sha: baseSha });
          const { data: emptyCommit } = await github.rest.git.createCommit({ owner, repo, message: "chore: initialize request", tree: baseTreeSha, parents: [baseSha] });
          await github.rest.git.updateRef({ owner, repo, ref: `heads/${finalBranch}`, sha: emptyCommit.sha });
          let body = "";
          if (background) body += "## Background\n\n" + background + "\n\n";
          if (approach) body += "## Approach\n\n" + approach + "\n";
          const prResp = await github.rest.pulls.create({ owner, repo, title, head: finalBranch, base: defaultBranch, body, draft: true });
          core.setOutput("branch_name", finalBranch);
          core.setOutput("pr_number", prResp.data.number);
          core.setOutput("pr_url", prResp.data.html_url);
