name: "Create Sprint"
description: "Create milestone and minimal sprint issues from templates"

inputs:
  version:
    description: "Version (e.g. v1.4.0)"
    required: true
  description:
    description: "Short sprint description"
    required: false

runs:
  using: "composite"
  steps:
    - name: Create Milestone and Issues
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          const version = "${{ inputs.version }}";
          const desc = "${{ inputs.description || '' }}";

          // Create milestone
          const milestone = await github.rest.issues.createMilestone({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: version,
            description: desc
          });

          const milestoneNumber = milestone.data.number;

          // Template directory (relative to action root)
          const templateDir = path.join(process.env.GITHUB_ACTION_PATH, 'templates');

          const files = fs.readdirSync(templateDir)
            .filter(f => f.endsWith('.md') && f !== 'README.md');

          for (const file of files) {
            const filePath = path.join(templateDir, file);
            const content = fs.readFileSync(filePath, 'utf8');

            const titleMatch = content.match(/^TITLE:\s*(.+)$/m);
            if (!titleMatch) {
              throw new Error(`Missing TITLE in ${file}`);
            }

            const title = titleMatch[1].replace('${version}', version);

            // Remove TITLE line from body
            const body = content.replace(/^TITLE:\s*.+$/m, '').trim();

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title.replace('${version}', version),
              body: body.replace(/\$\{version\}/g, version),
              milestone: milestoneNumber
            });
          }
